# sandbox zsh config
# History persists via the .persistent volume (symlinked by entrypoint)
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS

# fzf keybindings
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && source /usr/share/doc/fzf/examples/completion.zsh

# Source persistent env vars (npm prefix, etc.) set by entrypoint
[ -f /etc/profile.d/sandbox-persistent.sh ] && source /etc/profile.d/sandbox-persistent.sh

# git-delta config
export GIT_PAGER="delta --dark"

# prompt
PROMPT='%F{cyan}sandbox%f:%F{yellow}%~%f %# '
